name: main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  example:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      tag: ${{ steps.calver.outputs.tag }}
      version: ${{ steps.calver.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./
        id: calver
        with:
          commit-tag: 'false'

  usage:
    runs-on: ubuntu-latest
    needs: example
    steps:
    - run: |
        echo ${{ needs.example.outputs.tag }}
        echo ${{ needs.example.outputs.version }}
